#reference: https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=
newline_style = "Unix"
use_field_init_shorthand = true
match_block_trailing_comma = true
use_try_shorthand = true

#unstable -- can be used with nightly
combine_control_expr = false
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
inline_attribute_width = 50
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
wrap_comments = true